Class aaa.dev.v1.ep.a Extends %Persistent
{

Storage Default
{
<Data name="aDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^aaa.dev.v1.ep.aD</DataLocation>
<DefaultData>aDefaultData</DefaultData>
<IdLocation>^aaa.dev.v1.ep.aD</IdLocation>
<IndexLocation>^aaa.dev.v1.ep.aI</IndexLocation>
<StreamLocation>^aaa.dev.v1.ep.aS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
