Class aaa.dev.v1.ep.abc Extends %Persistent
{

Storage Default
{
<Data name="abcDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^aaa.dev.v1.ep.abcD</DataLocation>
<DefaultData>abcDefaultData</DefaultData>
<IdLocation>^aaa.dev.v1.ep.abcD</IdLocation>
<IndexLocation>^aaa.dev.v1.ep.abcI</IndexLocation>
<StreamLocation>^aaa.dev.v1.ep.abcS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
