# ARG IMAGE=containers.intersystems.com/intersystems/irishealth-community:2022.1.0.209.0
ARG IMAGE=localhost/intersystems/irishealth-ml-arm64:2022.1.1.374.0
ARG IMAGE=localhost/intersystems/irishealth-arm64:2022.2.0.368.0
ARG IMAGE=localhost/intersystems/iris-ml-arm64:2022.2.0.368.0
ARG IMAGE=containers.intersystems.com/intersystems/iris-community:2023.2.0.204.0
ARG IMAGE=containers.intersystems.com/intersystems/iris-community-arm64:2023.2.0.204.0
# ARG IMAGE=intersystemsdc/irishealth-community:latest
FROM $IMAGE
USER root
WORKDIR /app
RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /app
USER ${ISC_PACKAGE_MGRUSER}

COPY key/iris.key /usr/irissys/mgr/iris.key
COPY Installer.cls .
COPY src src
COPY iris.script /tmp/iris.script
COPY pdf /tmp/.
COPY requirements.txt .
COPY jdbc jdbc

USER ${ISC_PACKAGE_MGRUSER}

RUN pip3 install -r requirements.txt

RUN export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
RUN export PATH=$PATH:$JAVA_HOME/bin

ENV JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

RUN iris start IRIS \
	&& iris session IRIS < /tmp/iris.script \
    && iris stop IRIS quietly