### call REST API /admin/addwebapp via curl
curl -u _system:SYS http://localhost:52773/admin/addwebapp -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "webAppName": "/webappV2",
    "NameSpace": "IRISAPP",
    "Enabled": 1,
    "AutheEnabled": 32,
    "MatchRoles": ":%All",
    "LoginPage": "/webapp/web.zen.login.cls",
    "AutoCompile": 1,
    "CSPZENEnabled": 1,
    "CSRFToken": 1,
    "CookiePath": "/webapp",
    "IsNameSpaceDefault": 0,
    "Recurse": 1,
    "Type": 2
  }'