### call REST API /update/import via curl with basic auth in http header
curl -u _system:SYS http://localhost:52773/update/import/USER -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "directory": "/data/src" 
  }'





