### call REST API /update/import via curl
curl -u _system:SYS http://localhost:52773/update/import -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "namespace": "USER",
    "directory": "/data/src"
  }' 