Class aaa.dev.v1.ep.abcdef Extends %Persistent
{

Storage Default
{
<Data name="abcdefDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^aaa.dev.v1.ep.abcdefD</DataLocation>
<DefaultData>abcdefDefaultData</DefaultData>
<IdLocation>^aaa.dev.v1.ep.abcdefD</IdLocation>
<IndexLocation>^aaa.dev.v1.ep.abcdefI</IndexLocation>
<StreamLocation>^aaa.dev.v1.ep.abcdefS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
