/// 
Class data.RM.test Extends EnsLib.RecordMap.RecordMap
{

XData RecordMap [ XMLNamespace = "http://www.intersystems.com/Ensemble/RecordMap" ]
{
<Record xmlns="http://www.intersystems.com/Ensemble/RecordMap" name="data.RM.test" type="delimited" char_encoding="UTF-8" targetClassname="data.RM.test.Record" recordTerminator="\x0a">
  <Separators>
    <Separator>;</Separator>
  </Separators>
  <Field name="Property1" datatype="%String">
  </Field>
  <Field name="Property2" datatype="%String">
  </Field>
  <Field name="Property3" datatype="%String">
  </Field>
  <Field name="Property4" datatype="%String">
  </Field>
  <Field name="Property5" datatype="%String">
  </Field>
  <Field name="Property6" datatype="%String">
  </Field>
  <Field name="Property7" datatype="%String">
  </Field>
  <Field name="Property8" datatype="%String">
  </Field>
  <Field name="Property9" datatype="%String">
  </Field>
  <Field name="Property10" datatype="%String">
  </Field>
  <Field name="Property11" datatype="%String">
  </Field>
  <Field name="Property12" datatype="%String">
  </Field>
  <Field name="Property13" datatype="%String">
  </Field>
  <Field name="Property14" datatype="%String">
  </Field>
</Record>
}

}
