-- Création du schéma
CREATE USER supply IDENTIFIED BY supply_pwd;
GRANT CONNECT, RESOURCE TO supply;

-- Exemple de modèle Supply Chain
CREATE TABLE supply.products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    sku VARCHAR2(50),
    price NUMBER(10,2)
);

CREATE TABLE supply.orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES supply.products(id),
    quantity NUMBER,
    order_date DATE
);
