/// <p> created on 2023-07-28 16:38:20<p>generated automatically by <example>do ##class(large.utils).init()</example>
Class large.c10 Extends (%Persistent, %Populate, %XML.Adaptor, %JSON.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Property p1 As large.serial650;

Property p10 As large.serial650;

Property p2 As large.serial650;

Property p3 As large.serial650;

Property p4 As large.serial650;

Property p5 As large.serial650;

Property p6 As large.serial650;

Property p7 As large.serial650;

Property p8 As large.serial650;

Property p9 As large.serial650;

Storage Default
{
<Data name="c10DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>p1</Value>
</Value>
<Value name="3">
<Value>p10</Value>
</Value>
<Value name="4">
<Value>p2</Value>
</Value>
<Value name="5">
<Value>p3</Value>
</Value>
<Value name="6">
<Value>p4</Value>
</Value>
<Value name="7">
<Value>p5</Value>
</Value>
<Value name="8">
<Value>p6</Value>
</Value>
<Value name="9">
<Value>p7</Value>
</Value>
<Value name="10">
<Value>p8</Value>
</Value>
<Value name="11">
<Value>p9</Value>
</Value>
</Data>
<DataLocation>^large.c10D</DataLocation>
<DefaultData>c10DefaultData</DefaultData>
<IdLocation>^large.c10D</IdLocation>
<IndexLocation>^large.c10I</IndexLocation>
<StreamLocation>^large.c10S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
