/// <p> created on 2023-07-28 16:31:21<p>generated automatically by <example>do ##class(large.utils).init()</example>
Class large.c100 Extends (%Persistent, %Populate, %XML.Adaptor, %JSON.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Property p1 As large.serial;

Property p10 As large.serial;

Property p100 As large.serial;

Property p11 As large.serial;

Property p12 As large.serial;

Property p13 As large.serial;

Property p14 As large.serial;

Property p15 As large.serial;

Property p16 As large.serial;

Property p17 As large.serial;

Property p18 As large.serial;

Property p19 As large.serial;

Property p2 As large.serial;

Property p20 As large.serial;

Property p21 As large.serial;

Property p22 As large.serial;

Property p23 As large.serial;

Property p24 As large.serial;

Property p25 As large.serial;

Property p26 As large.serial;

Property p27 As large.serial;

Property p28 As large.serial;

Property p29 As large.serial;

Property p3 As large.serial;

Property p30 As large.serial;

Property p31 As large.serial;

Property p32 As large.serial;

Property p33 As large.serial;

Property p34 As large.serial;

Property p35 As large.serial;

Property p36 As large.serial;

Property p37 As large.serial;

Property p38 As large.serial;

Property p39 As large.serial;

Property p4 As large.serial;

Property p40 As large.serial;

Property p41 As large.serial;

Property p42 As large.serial;

Property p43 As large.serial;

Property p44 As large.serial;

Property p45 As large.serial;

Property p46 As large.serial;

Property p47 As large.serial;

Property p48 As large.serial;

Property p49 As large.serial;

Property p5 As large.serial;

Property p50 As large.serial;

Property p51 As large.serial;

Property p52 As large.serial;

Property p53 As large.serial;

Property p54 As large.serial;

Property p55 As large.serial;

Property p56 As large.serial;

Property p57 As large.serial;

Property p58 As large.serial;

Property p59 As large.serial;

Property p6 As large.serial;

Property p60 As large.serial;

Property p61 As large.serial;

Property p62 As large.serial;

Property p63 As large.serial;

Property p64 As large.serial;

Property p65 As large.serial;

Property p66 As large.serial;

Property p67 As large.serial;

Property p68 As large.serial;

Property p69 As large.serial;

Property p7 As large.serial;

Property p70 As large.serial;

Property p71 As large.serial;

Property p72 As large.serial;

Property p73 As large.serial;

Property p74 As large.serial;

Property p75 As large.serial;

Property p76 As large.serial;

Property p77 As large.serial;

Property p78 As large.serial;

Property p79 As large.serial;

Property p8 As large.serial;

Property p80 As large.serial;

Property p81 As large.serial;

Property p82 As large.serial;

Property p83 As large.serial;

Property p84 As large.serial;

Property p85 As large.serial;

Property p86 As large.serial;

Property p87 As large.serial;

Property p88 As large.serial;

Property p89 As large.serial;

Property p9 As large.serial;

Property p90 As large.serial;

Property p91 As large.serial;

Property p92 As large.serial;

Property p93 As large.serial;

Property p94 As large.serial;

Property p95 As large.serial;

Property p96 As large.serial;

Property p97 As large.serial;

Property p98 As large.serial;

Property p99 As large.serial;

Storage Default
{
<Data name="c100DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>p1</Value>
</Value>
<Value name="3">
<Value>p10</Value>
</Value>
<Value name="4">
<Value>p100</Value>
</Value>
<Value name="5">
<Value>p11</Value>
</Value>
<Value name="6">
<Value>p12</Value>
</Value>
<Value name="7">
<Value>p13</Value>
</Value>
<Value name="8">
<Value>p14</Value>
</Value>
<Value name="9">
<Value>p15</Value>
</Value>
<Value name="10">
<Value>p16</Value>
</Value>
<Value name="11">
<Value>p17</Value>
</Value>
<Value name="12">
<Value>p18</Value>
</Value>
<Value name="13">
<Value>p19</Value>
</Value>
<Value name="14">
<Value>p2</Value>
</Value>
<Value name="15">
<Value>p20</Value>
</Value>
<Value name="16">
<Value>p21</Value>
</Value>
<Value name="17">
<Value>p22</Value>
</Value>
<Value name="18">
<Value>p23</Value>
</Value>
<Value name="19">
<Value>p24</Value>
</Value>
<Value name="20">
<Value>p25</Value>
</Value>
<Value name="21">
<Value>p26</Value>
</Value>
<Value name="22">
<Value>p27</Value>
</Value>
<Value name="23">
<Value>p28</Value>
</Value>
<Value name="24">
<Value>p29</Value>
</Value>
<Value name="25">
<Value>p3</Value>
</Value>
<Value name="26">
<Value>p30</Value>
</Value>
<Value name="27">
<Value>p31</Value>
</Value>
<Value name="28">
<Value>p32</Value>
</Value>
<Value name="29">
<Value>p33</Value>
</Value>
<Value name="30">
<Value>p34</Value>
</Value>
<Value name="31">
<Value>p35</Value>
</Value>
<Value name="32">
<Value>p36</Value>
</Value>
<Value name="33">
<Value>p37</Value>
</Value>
<Value name="34">
<Value>p38</Value>
</Value>
<Value name="35">
<Value>p39</Value>
</Value>
<Value name="36">
<Value>p4</Value>
</Value>
<Value name="37">
<Value>p40</Value>
</Value>
<Value name="38">
<Value>p41</Value>
</Value>
<Value name="39">
<Value>p42</Value>
</Value>
<Value name="40">
<Value>p43</Value>
</Value>
<Value name="41">
<Value>p44</Value>
</Value>
<Value name="42">
<Value>p45</Value>
</Value>
<Value name="43">
<Value>p46</Value>
</Value>
<Value name="44">
<Value>p47</Value>
</Value>
<Value name="45">
<Value>p48</Value>
</Value>
<Value name="46">
<Value>p49</Value>
</Value>
<Value name="47">
<Value>p5</Value>
</Value>
<Value name="48">
<Value>p50</Value>
</Value>
<Value name="49">
<Value>p51</Value>
</Value>
<Value name="50">
<Value>p52</Value>
</Value>
<Value name="51">
<Value>p53</Value>
</Value>
<Value name="52">
<Value>p54</Value>
</Value>
<Value name="53">
<Value>p55</Value>
</Value>
<Value name="54">
<Value>p56</Value>
</Value>
<Value name="55">
<Value>p57</Value>
</Value>
<Value name="56">
<Value>p58</Value>
</Value>
<Value name="57">
<Value>p59</Value>
</Value>
<Value name="58">
<Value>p6</Value>
</Value>
<Value name="59">
<Value>p60</Value>
</Value>
<Value name="60">
<Value>p61</Value>
</Value>
<Value name="61">
<Value>p62</Value>
</Value>
<Value name="62">
<Value>p63</Value>
</Value>
<Value name="63">
<Value>p64</Value>
</Value>
<Value name="64">
<Value>p65</Value>
</Value>
<Value name="65">
<Value>p66</Value>
</Value>
<Value name="66">
<Value>p67</Value>
</Value>
<Value name="67">
<Value>p68</Value>
</Value>
<Value name="68">
<Value>p69</Value>
</Value>
<Value name="69">
<Value>p7</Value>
</Value>
<Value name="70">
<Value>p70</Value>
</Value>
<Value name="71">
<Value>p71</Value>
</Value>
<Value name="72">
<Value>p72</Value>
</Value>
<Value name="73">
<Value>p73</Value>
</Value>
<Value name="74">
<Value>p74</Value>
</Value>
<Value name="75">
<Value>p75</Value>
</Value>
<Value name="76">
<Value>p76</Value>
</Value>
<Value name="77">
<Value>p77</Value>
</Value>
<Value name="78">
<Value>p78</Value>
</Value>
<Value name="79">
<Value>p79</Value>
</Value>
<Value name="80">
<Value>p8</Value>
</Value>
<Value name="81">
<Value>p80</Value>
</Value>
<Value name="82">
<Value>p81</Value>
</Value>
<Value name="83">
<Value>p82</Value>
</Value>
<Value name="84">
<Value>p83</Value>
</Value>
<Value name="85">
<Value>p84</Value>
</Value>
<Value name="86">
<Value>p85</Value>
</Value>
<Value name="87">
<Value>p86</Value>
</Value>
<Value name="88">
<Value>p87</Value>
</Value>
<Value name="89">
<Value>p88</Value>
</Value>
<Value name="90">
<Value>p89</Value>
</Value>
<Value name="91">
<Value>p9</Value>
</Value>
<Value name="92">
<Value>p90</Value>
</Value>
<Value name="93">
<Value>p91</Value>
</Value>
<Value name="94">
<Value>p92</Value>
</Value>
<Value name="95">
<Value>p93</Value>
</Value>
<Value name="96">
<Value>p94</Value>
</Value>
<Value name="97">
<Value>p95</Value>
</Value>
<Value name="98">
<Value>p96</Value>
</Value>
<Value name="99">
<Value>p97</Value>
</Value>
<Value name="100">
<Value>p98</Value>
</Value>
<Value name="101">
<Value>p99</Value>
</Value>
</Data>
<DataLocation>^large.c100D</DataLocation>
<DefaultData>c100DefaultData</DefaultData>
<IdLocation>^large.c100D</IdLocation>
<IndexLocation>^large.c100I</IndexLocation>
<StreamLocation>^large.c100S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
