/// <p> created on 2023-07-28 16:38:07<p>generated automatically by <example>do ##class(large.utils).init()</example>
Class large.c5 Extends (%Persistent, %Populate, %XML.Adaptor, %JSON.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Property p1 As large.serial900;

Property p2 As large.serial900;

Property p3 As large.serial900;

Property p4 As large.serial900;

Property p5 As large.serial900;

Storage Default
{
<Data name="c5DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>p1</Value>
</Value>
<Value name="3">
<Value>p2</Value>
</Value>
<Value name="4">
<Value>p3</Value>
</Value>
<Value name="5">
<Value>p4</Value>
</Value>
<Value name="6">
<Value>p5</Value>
</Value>
</Data>
<DataLocation>^large.c5D</DataLocation>
<DefaultData>c5DefaultData</DefaultData>
<IdLocation>^large.c5D</IdLocation>
<IndexLocation>^large.c5I</IndexLocation>
<StreamLocation>^large.c5S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
