/// <p> created on 2023-07-28 16:35:58<p>generated automatically by <example>do ##class(large.utils).init()</example>
Class large.serial Extends (%SerialObject, %Populate, %XML.Adaptor, %JSON.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Property s1 As %String(MAXLEN = "");

Property s10 As %String(MAXLEN = "");

Property s100 As %String(MAXLEN = "");

Property s11 As %String(MAXLEN = "");

Property s12 As %String(MAXLEN = "");

Property s13 As %String(MAXLEN = "");

Property s14 As %String(MAXLEN = "");

Property s15 As %String(MAXLEN = "");

Property s16 As %String(MAXLEN = "");

Property s17 As %String(MAXLEN = "");

Property s18 As %String(MAXLEN = "");

Property s19 As %String(MAXLEN = "");

Property s2 As %String(MAXLEN = "");

Property s20 As %String(MAXLEN = "");

Property s21 As %String(MAXLEN = "");

Property s22 As %String(MAXLEN = "");

Property s23 As %String(MAXLEN = "");

Property s24 As %String(MAXLEN = "");

Property s25 As %String(MAXLEN = "");

Property s26 As %String(MAXLEN = "");

Property s27 As %String(MAXLEN = "");

Property s28 As %String(MAXLEN = "");

Property s29 As %String(MAXLEN = "");

Property s3 As %String(MAXLEN = "");

Property s30 As %String(MAXLEN = "");

Property s31 As %String(MAXLEN = "");

Property s32 As %String(MAXLEN = "");

Property s33 As %String(MAXLEN = "");

Property s34 As %String(MAXLEN = "");

Property s35 As %String(MAXLEN = "");

Property s36 As %String(MAXLEN = "");

Property s37 As %String(MAXLEN = "");

Property s38 As %String(MAXLEN = "");

Property s39 As %String(MAXLEN = "");

Property s4 As %String(MAXLEN = "");

Property s40 As %String(MAXLEN = "");

Property s41 As %String(MAXLEN = "");

Property s42 As %String(MAXLEN = "");

Property s43 As %String(MAXLEN = "");

Property s44 As %String(MAXLEN = "");

Property s45 As %String(MAXLEN = "");

Property s46 As %String(MAXLEN = "");

Property s47 As %String(MAXLEN = "");

Property s48 As %String(MAXLEN = "");

Property s49 As %String(MAXLEN = "");

Property s5 As %String(MAXLEN = "");

Property s50 As %String(MAXLEN = "");

Property s51 As %String(MAXLEN = "");

Property s52 As %String(MAXLEN = "");

Property s53 As %String(MAXLEN = "");

Property s54 As %String(MAXLEN = "");

Property s55 As %String(MAXLEN = "");

Property s56 As %String(MAXLEN = "");

Property s57 As %String(MAXLEN = "");

Property s58 As %String(MAXLEN = "");

Property s59 As %String(MAXLEN = "");

Property s6 As %String(MAXLEN = "");

Property s60 As %String(MAXLEN = "");

Property s61 As %String(MAXLEN = "");

Property s62 As %String(MAXLEN = "");

Property s63 As %String(MAXLEN = "");

Property s64 As %String(MAXLEN = "");

Property s65 As %String(MAXLEN = "");

Property s66 As %String(MAXLEN = "");

Property s67 As %String(MAXLEN = "");

Property s68 As %String(MAXLEN = "");

Property s69 As %String(MAXLEN = "");

Property s7 As %String(MAXLEN = "");

Property s70 As %String(MAXLEN = "");

Property s71 As %String(MAXLEN = "");

Property s72 As %String(MAXLEN = "");

Property s73 As %String(MAXLEN = "");

Property s74 As %String(MAXLEN = "");

Property s75 As %String(MAXLEN = "");

Property s76 As %String(MAXLEN = "");

Property s77 As %String(MAXLEN = "");

Property s78 As %String(MAXLEN = "");

Property s79 As %String(MAXLEN = "");

Property s8 As %String(MAXLEN = "");

Property s80 As %String(MAXLEN = "");

Property s81 As %String(MAXLEN = "");

Property s82 As %String(MAXLEN = "");

Property s83 As %String(MAXLEN = "");

Property s84 As %String(MAXLEN = "");

Property s85 As %String(MAXLEN = "");

Property s86 As %String(MAXLEN = "");

Property s87 As %String(MAXLEN = "");

Property s88 As %String(MAXLEN = "");

Property s89 As %String(MAXLEN = "");

Property s9 As %String(MAXLEN = "");

Property s90 As %String(MAXLEN = "");

Property s91 As %String(MAXLEN = "");

Property s92 As %String(MAXLEN = "");

Property s93 As %String(MAXLEN = "");

Property s94 As %String(MAXLEN = "");

Property s95 As %String(MAXLEN = "");

Property s96 As %String(MAXLEN = "");

Property s97 As %String(MAXLEN = "");

Property s98 As %String(MAXLEN = "");

Property s99 As %String(MAXLEN = "");

Storage Default
{
<Data name="serialState">
<Value name="1">
<Value>s1</Value>
</Value>
<Value name="2">
<Value>s10</Value>
</Value>
<Value name="3">
<Value>s100</Value>
</Value>
<Value name="4">
<Value>s11</Value>
</Value>
<Value name="5">
<Value>s12</Value>
</Value>
<Value name="6">
<Value>s13</Value>
</Value>
<Value name="7">
<Value>s14</Value>
</Value>
<Value name="8">
<Value>s15</Value>
</Value>
<Value name="9">
<Value>s16</Value>
</Value>
<Value name="10">
<Value>s17</Value>
</Value>
<Value name="11">
<Value>s18</Value>
</Value>
<Value name="12">
<Value>s19</Value>
</Value>
<Value name="13">
<Value>s2</Value>
</Value>
<Value name="14">
<Value>s20</Value>
</Value>
<Value name="15">
<Value>s21</Value>
</Value>
<Value name="16">
<Value>s22</Value>
</Value>
<Value name="17">
<Value>s23</Value>
</Value>
<Value name="18">
<Value>s24</Value>
</Value>
<Value name="19">
<Value>s25</Value>
</Value>
<Value name="20">
<Value>s26</Value>
</Value>
<Value name="21">
<Value>s27</Value>
</Value>
<Value name="22">
<Value>s28</Value>
</Value>
<Value name="23">
<Value>s29</Value>
</Value>
<Value name="24">
<Value>s3</Value>
</Value>
<Value name="25">
<Value>s30</Value>
</Value>
<Value name="26">
<Value>s31</Value>
</Value>
<Value name="27">
<Value>s32</Value>
</Value>
<Value name="28">
<Value>s33</Value>
</Value>
<Value name="29">
<Value>s34</Value>
</Value>
<Value name="30">
<Value>s35</Value>
</Value>
<Value name="31">
<Value>s36</Value>
</Value>
<Value name="32">
<Value>s37</Value>
</Value>
<Value name="33">
<Value>s38</Value>
</Value>
<Value name="34">
<Value>s39</Value>
</Value>
<Value name="35">
<Value>s4</Value>
</Value>
<Value name="36">
<Value>s40</Value>
</Value>
<Value name="37">
<Value>s41</Value>
</Value>
<Value name="38">
<Value>s42</Value>
</Value>
<Value name="39">
<Value>s43</Value>
</Value>
<Value name="40">
<Value>s44</Value>
</Value>
<Value name="41">
<Value>s45</Value>
</Value>
<Value name="42">
<Value>s46</Value>
</Value>
<Value name="43">
<Value>s47</Value>
</Value>
<Value name="44">
<Value>s48</Value>
</Value>
<Value name="45">
<Value>s49</Value>
</Value>
<Value name="46">
<Value>s5</Value>
</Value>
<Value name="47">
<Value>s50</Value>
</Value>
<Value name="48">
<Value>s51</Value>
</Value>
<Value name="49">
<Value>s52</Value>
</Value>
<Value name="50">
<Value>s53</Value>
</Value>
<Value name="51">
<Value>s54</Value>
</Value>
<Value name="52">
<Value>s55</Value>
</Value>
<Value name="53">
<Value>s56</Value>
</Value>
<Value name="54">
<Value>s57</Value>
</Value>
<Value name="55">
<Value>s58</Value>
</Value>
<Value name="56">
<Value>s59</Value>
</Value>
<Value name="57">
<Value>s6</Value>
</Value>
<Value name="58">
<Value>s60</Value>
</Value>
<Value name="59">
<Value>s61</Value>
</Value>
<Value name="60">
<Value>s62</Value>
</Value>
<Value name="61">
<Value>s63</Value>
</Value>
<Value name="62">
<Value>s64</Value>
</Value>
<Value name="63">
<Value>s65</Value>
</Value>
<Value name="64">
<Value>s66</Value>
</Value>
<Value name="65">
<Value>s67</Value>
</Value>
<Value name="66">
<Value>s68</Value>
</Value>
<Value name="67">
<Value>s69</Value>
</Value>
<Value name="68">
<Value>s7</Value>
</Value>
<Value name="69">
<Value>s70</Value>
</Value>
<Value name="70">
<Value>s71</Value>
</Value>
<Value name="71">
<Value>s72</Value>
</Value>
<Value name="72">
<Value>s73</Value>
</Value>
<Value name="73">
<Value>s74</Value>
</Value>
<Value name="74">
<Value>s75</Value>
</Value>
<Value name="75">
<Value>s76</Value>
</Value>
<Value name="76">
<Value>s77</Value>
</Value>
<Value name="77">
<Value>s78</Value>
</Value>
<Value name="78">
<Value>s79</Value>
</Value>
<Value name="79">
<Value>s8</Value>
</Value>
<Value name="80">
<Value>s80</Value>
</Value>
<Value name="81">
<Value>s81</Value>
</Value>
<Value name="82">
<Value>s82</Value>
</Value>
<Value name="83">
<Value>s83</Value>
</Value>
<Value name="84">
<Value>s84</Value>
</Value>
<Value name="85">
<Value>s85</Value>
</Value>
<Value name="86">
<Value>s86</Value>
</Value>
<Value name="87">
<Value>s87</Value>
</Value>
<Value name="88">
<Value>s88</Value>
</Value>
<Value name="89">
<Value>s89</Value>
</Value>
<Value name="90">
<Value>s9</Value>
</Value>
<Value name="91">
<Value>s90</Value>
</Value>
<Value name="92">
<Value>s91</Value>
</Value>
<Value name="93">
<Value>s92</Value>
</Value>
<Value name="94">
<Value>s93</Value>
</Value>
<Value name="95">
<Value>s94</Value>
</Value>
<Value name="96">
<Value>s95</Value>
</Value>
<Value name="97">
<Value>s96</Value>
</Value>
<Value name="98">
<Value>s97</Value>
</Value>
<Value name="99">
<Value>s98</Value>
</Value>
<Value name="100">
<Value>s99</Value>
</Value>
</Data>
<State>serialState</State>
<StreamLocation>^large.serialS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
